config/routes.rb
Tienda3::Application.routes.draw do
  get "tienda/index"

  resources :carro_lineas

  resources :carros

  resources :productos

  root :to => 'tienda#index'

end

app/models/carro.rb
class Carro < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :carro_lineas, dependent: :destroy
end

app/models/carro_linea.rb
class CarroLinea < ActiveRecord::Base
  attr_accessible :carro_id, :producto_id

  belongs_to :carro
  belongs_to :producto
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :descripcion, :imagen_url, :nombre, :precio

  has_many :carro_lineas

  validates :nombre, :descripcion, presence: true

  validates :precio, numericality: {greater_than_or_equal_to: 0.01}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def carro_actual

  	begin

  		carro = Carro.find(session[:carro_id])

  	rescue

  		carro = Carro.create

  		session[:carro_id] = carro.id

  	end

  	carro

  end

end

app/controllers/carro_lineas_controller.rb
class CarroLineasController < ApplicationController
  # GET /carro_lineas
  # GET /carro_lineas.json
  def index
    @carro_lineas = CarroLinea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carro_lineas }
    end
  end

  # GET /carro_lineas/1
  # GET /carro_lineas/1.json
  def show
    @carro_linea = CarroLinea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @carro_linea }
    end
  end

  # GET /carro_lineas/new
  # GET /carro_lineas/new.json
  def new
    @carro_linea = CarroLinea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @carro_linea }
    end
  end

  # GET /carro_lineas/1/edit
  def edit
    @carro_linea = CarroLinea.find(params[:id])
  end

  # POST /carro_lineas
  # POST /carro_lineas.json
  def create

    debugger

    @carro = carro_actual

    @producto = Producto.find(params[:producto_id])

    @carro_linea = CarroLinea.new

    @carro_linea.carro_id = @carro.id
    @carro_linea.producto_id = @producto.id

    respond_to do |format|
      if @carro_linea.save
        format.html { redirect_to @carro_linea, notice: 'Carro linea was successfully created.' }
        format.json { render json: @carro_linea, status: :created, location: @carro_linea }
      else
        format.html { render action: "new" }
        format.json { render json: @carro_linea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carro_lineas/1
  # PUT /carro_lineas/1.json
  def update
    @carro_linea = CarroLinea.find(params[:id])

    respond_to do |format|
      if @carro_linea.update_attributes(params[:carro_linea])
        format.html { redirect_to @carro_linea, notice: 'Carro linea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @carro_linea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carro_lineas/1
  # DELETE /carro_lineas/1.json
  def destroy
    @carro_linea = CarroLinea.find(params[:id])
    @carro_linea.destroy

    respond_to do |format|
      format.html { redirect_to carro_lineas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carros }
    end
  end

  # GET /carros/1
  # GET /carros/1.json
  def show
    @carro = Carro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @carro }
    end
  end

  # GET /carros/new
  # GET /carros/new.json
  def new
    @carro = Carro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @carro }
    end
  end

  # GET /carros/1/edit
  def edit
    @carro = Carro.find(params[:id])
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(params[:carro])

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render json: @carro, status: :created, location: @carro }
      else
        format.html { render action: "new" }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carros/1
  # PUT /carros/1.json
  def update
    @carro = Carro.find(params[:id])

    respond_to do |format|
      if @carro.update_attributes(params[:carro])
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro = Carro.find(params[:id])
    @carro.destroy

    respond_to do |format|
      format.html { redirect_to carros_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tienda_controller.rb
class TiendaController < ApplicationController
  def index
  	@productos = Producto.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carro_lineas_helper.rb
module CarroLineasHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tienda_helper.rb
module TiendaHelper
end

app/views/carro_lineas/_form.html.erb
<%= form_for(@carro_linea) do |f| %>
  <% if @carro_linea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro_linea.errors.count, "error") %> prohibited this carro_linea from being saved:</h2>

      <ul>
      <% @carro_linea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto_id %><br />
    <%= f.number_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :carro_id %><br />
    <%= f.number_field :carro_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carro_lineas/edit.html.erb
<h1>Editing carro_linea</h1>

<%= render 'form' %>

<%= link_to 'Show', @carro_linea %> |
<%= link_to 'Back', carro_lineas_path %>

app/views/carro_lineas/index.html.erb
<h1>Listing carro_lineas</h1>

<table>
  <tr>
    <th>Producto</th>
    <th>Carro</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carro_lineas.each do |carro_linea| %>
  <tr>
    <td><%= carro_linea.producto_id %></td>
    <td><%= carro_linea.carro_id %></td>
    <td><%= link_to 'Show', carro_linea %></td>
    <td><%= link_to 'Edit', edit_carro_linea_path(carro_linea) %></td>
    <td><%= link_to 'Destroy', carro_linea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Carro linea', new_carro_linea_path %>

app/views/carro_lineas/new.html.erb
<h1>New carro_linea</h1>

<%= render 'form' %>

<%= link_to 'Back', carro_lineas_path %>

app/views/carro_lineas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producto:</b>
  <%= @carro_linea.producto_id %>
</p>

<p>
  <b>Carro:</b>
  <%= @carro_linea.carro_id %>
</p>


<%= link_to 'Edit', edit_carro_linea_path(@carro_linea) %> |
<%= link_to 'Back', carro_lineas_path %>

app/views/carros/_form.html.erb
<%= form_for(@carro) do |f| %>
  <% if @carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% @carro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render 'form' %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<h1>Listing carros</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carros.each do |carro| %>
  <tr>
    <td><%= link_to 'Show', carro %></td>
    <td><%= link_to 'Edit', edit_carro_path(carro) %></td>
    <td><%= link_to 'Destroy', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Carro', new_carro_path %>

app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render 'form' %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name%>">

<%= yield %>

</body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :imagen_url %><br />
    <%= f.text_field :imagen_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Precio</th>
    <th>Imagen url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr class="<%= cycle('impar','par') %>">
    <td><%= producto.nombre %></td>
    <td><%= producto.descripcion %></td>
    <td><%= producto.precio %></td>
    <td><%= producto.imagen_url %></td>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= truncate @producto.descripcion, length: 10 %>
</p>

<p>
  <b>Precio:</b>
  <%= number_to_currency(@producto.precio, unit: '€', format: "%n %u") %>
</p>

<p>
  <b>Imagen url:</b>
  <%= @producto.imagen_url %>
</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/tienda/index.html.erb
<h1>Mi tienda</h1>

<ul>
	<% @productos.each do |producto| %>

		<li>
			<%= producto.nombre %>
			<%= button_to 'Añadir al carro', carro_lineas_path(producto_id: producto.id) %>
		</li>

	<% end %>
</ul>